### ISSUE TITLE
UI API called on a background thread Warning

### ISSUE THREAD

**Issue by LeoSnek** [bluecats/bluecats-ios-sdk#12]
I'm getting some UI thread errors when I initialise my `BCBeaconmanager`:

    Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
    PID: 74541, TID: 4961298, Thread name: (none), Queue name: com.bluecats.sessionManager, QoS: 0
    Backtrace:
    4   MyApp                            0x0000000109ec6e27 +[BCDefinitionsInternal isAppInBackground] + 55
    5   MyApp                            0x0000000109f3bb8e -[BCScanManager updateScanState] + 43
    6   CoreFoundation                      0x000000010efbdbac __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
    7   CoreFoundation                      0x000000010efbd02f _CFXRegistrationPost + 447
    8   CoreFoundation                      0x000000010efbcd71 ___CFXNotificationPost_block_invoke + 225
    9   CoreFoundation                      0x000000010f0a3ae2 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1826
    10  CoreFoundation                      0x000000010efbc694 _CFXNotificationPost + 964
    11  Foundation                          0x000000010cf12589 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
    12  MyApp                            0x0000000109f42006 -[BCSessionManager resumeSession] + 272
    13  MyApp                            0x0000000109f42084 -[BCSessionManager resumeOrBeginSession] + 40
    14  libdispatch.dylib                   0x00000001114b9595 _dispatch_call_block_and_release + 12
    15  libdispatch.dylib                   0x00000001114ba602 _dispatch_client_callout + 8
    16  libdispatch.dylib                   0x00000001114c1b0b _dispatch_lane_serial_drain + 791
    17  libdispatch.dylib                   0x00000001114c2784 _dispatch_lane_invoke + 428
    18  libdispatch.dylib                   0x00000001114cc89a _dispatch_workloop_worker_thread + 733
    19  libsystem_pthread.dylib             0x00000001118a5fd2 _pthread_wqthread + 980
    20  libsystem_pthread.dylib             0x00000001118a5be9 start_wqthread + 13
    2019-01-28 16:29:25.713940+0000 MyApp[74541:4961298] [reports] Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
    PID: 74541, TID: 4961298, Thread name: (none), Queue name: com.bluecats.sessionManager, QoS: 0
    Backtrace:
    4   MyApp                            0x0000000109ec6e27 +[BCDefinitionsInternal isAppInBackground] + 55
    5   MyApp                            0x0000000109f3bb8e -[BCScanManager updateScanState] + 43
    6   CoreFoundation                      0x000000010efbdbac __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
    7   CoreFoundation                      0x000000010efbd02f _CFXRegistrationPost + 447
    8   CoreFoundation                      0x000000010efbcd71 ___CFXNotificationPost_block_invoke + 225
    9   CoreFoundation                      0x000000010f0a3ae2 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1826
    10  CoreFoundation                      0x000000010efbc694 _CFXNotificationPost + 964
    11  Foundation                          0x000000010cf12589 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
    12  MyApp                            0x0000000109f42006 -[BCSessionManager resumeSession] + 272
    13  MyApp                            0x0000000109f42084 -[BCSessionManager resumeOrBeginSession] + 40
    14  libdispatch.dylib                   0x00000001114b9595 _dispatch_call_block_and_release + 12
    15  libdispatch.dylib                   0x00000001114ba602 _dispatch_client_callout + 8
    16  libdispatch.dylib                   0x00000001114c1b0b _dispatch_lane_serial_drain + 791
    17  libdispatch.dylib                   0x00000001114c2784 _dispatch_lane_invoke + 428
    18  libdispatch.dylib                   0x00000001114cc89a _dispatch_workloop_worker_thread + 733
    19  libsystem_pthread.dylib             0x00000001118a5fd2 _pthread_wqthread + 980
    20  libsystem_pthread.dylib             0x00000001118a5be9 start_wqthread + 13

**Comment by damoclarke** [comment]
Hi @LeoSnek. We have a new stability release out this week that includes a fix for that warning. Please try the latest and let me know if you still have any problems.
