### ISSUE TITLE
Bug in the Bluecats iOS SDK

### ISSUE THREAD

**Issue by leonidmelnik** [bluecats/bluecats-ios-sdk#8]
I've found the bug. I've noticed that sometimes (especially after deleting and reinstalling my app) I cannot update microlocation. What I do:
1) Create instance of BCMicroLocationManager and set a delegate:
```
self.microLocationManager = [[BCMicroLocationManager alloc] init];
self.microLocationManager.delegate = self;
```
2) Start purring with method `+[BlueCatsSDK startPurringWithAppToken:completion:]`
3) If all good then I start updating microlocation:
[self.microLocationManager startUpdatingMicroLocation];
4) I've implemented microLocationManager:didUpdateMicroLocations: for BCMicroLocationManager delegate but SDK doesn't call this method :(
How I've fixed it:
I've updated purring method:
```
[BlueCatsSDK startPurringWithAppToken:@"the_token" completion:^(BCStatus status) {
    [[BlueCatsSDK currentApp] getBeaconsWithSuccess:^(NSArray* beacons) {
        NSLog(@"BEACONS:\n%@", beacons);
    } failure:^(NSError* error) {
        NSLog(@"BEACONS ERROR: %@", error);
    } preferCached:NO];
}];
```
and after that the SDK started calling method of the delegate.

I suppose that Bluecats iOS SDK has a bug. Maybe I do something wrong (or in incorrect sequence)? Could you please advise or fix this bug?

**Comment by caseycoding** [comment]
Hi Leonid,

When you are initially calling [BlueCatsSDK startPurringWithAppToken:completion:] are you passing in your app token and completion block as in https://developer.bluecats.com/guides/startpurring#ios?

**Comment by leonidmelnik** [comment]
> When you are initially calling [BlueCatsSDK startPurringWithAppToken:completion:] are you passing in your app token and completion block

Sure, the code wouldn't work if I haven't passed the app token :)

> Also would you mind posting your initial code that doesn't work?

```
- (void)startMonitoring
{
	self.microLocationManager = [[BCMicroLocationManager alloc] init];
	self.microLocationManager.delegate = self;
	
	BCStatus status = [BlueCatsSDK status];
	switch(status)
	{
		case kBCStatusNeverPurred:
		case kBCStatusPurringWithErrors:
		{
			[BlueCatsSDK startPurringWithAppToken:@"the_token" completion:^(BCStatus status) {
				if(status == kBCStatusPurringWithErrors)
				{
					NSLog(@"STARTED WITH ERRORS!");
					if(![BlueCatsSDK isLocationAuthorized])
						[BlueCatsSDK requestWhenInUseLocationAuthorization];
					if(![BlueCatsSDK isNetworkReachable])
					{
						NSError* error = [NSError errorWithDomain:@"TLA"
															 code:0
														 userInfo:@{NSLocalizedDescriptionKey : @"Please check your network connection."}];
						[[TLBackendClient sharedClient] openRetryAlertWithRequest:nil
																		  failure:nil
																			error:error];
					}
				}
				else
				{
					NSLog(@"STARTED WITHOUT ERRORS!");
					[self.microLocationManager startUpdatingMicroLocation];
				}
			}];
			break;
		}
		case kBCStatusPurring:
			// Do nothing
			break;
	}
}

- (void)microLocationManager:(BCMicroLocationManager *)microLocationManager didUpdateMicroLocations:(NSArray *)microLocations
{
	NSLog(@"%@::%@", NSStringFromClass([self class]), NSStringFromSelector(_cmd));
	self.currentBeacons = microLocationManager.microLocation.beacons;
	[self updateZone];
}
```

There is a string in the console `App[4407:1777955] STARTED WITHOUT ERRORS!` but SDK doesn't call delegate's method

**Comment by caseycoding** [comment]
Hi Leonid,

We are spotting a few possible issues with the code you've posted.

Creating the the microlocationManager before the SDK is fully initialized may give you some issues.

`startPurring` internally handles cases where it's called multiple times so you shouldn't have to handle this yourself.  We would suggest changing your code to something more along these lines:

```objc
- (void)startMonitoring
{
  [BlueCatsSDK startPurringWithAppToken:@"the_token" completion:^(BCStatus status) {
      if(status == kBCStatusPurringWithErrors)
      {
          NSLog(@"STARTED WITH ERRORS!");
          if(![BlueCatsSDK isLocationAuthorized])
              [BlueCatsSDK requestWhenInUseLocationAuthorization];
          if(![BlueCatsSDK isNetworkReachable])
          {
              NSError* error = [NSError errorWithDomain:@"TLA"
                                                   code:0
                                               userInfo:@{NSLocalizedDescriptionKey : @"Please check your network connection."}];
              [[TLBackendClient sharedClient] openRetryAlertWithRequest:nil
                                                                failure:nil
                                                                  error:error];
          }
      }
      self.microLocationManager = [[BCMicroLocationManager alloc] init];
      self.microLocationManager.delegate = self;
      [self.microLocationManager startUpdatingMicroLocation];
  }];
}
```
We've removed the if-else condition due to a concern that if the SDK does start purring with errors - such as the user hasn't granted location access - startUpdatingMicroLocation isn't called until the function is run again (and there aren't errors).

Please let us know if you have any questions about this!

**Comment by caseycoding** [comment]
Hi Leonid,

I'm going to go ahead and close this issue.  Please let us know if you still have any questions!
